// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIgUrn6nmXaEwi7DZknH4Vm0Cd5sI-uZw',
    appId: '1:121552352022:web:b24745527f702a3ba89637',
    messagingSenderId: '121552352022',
    projectId: 'no-excuses-f5c0f',
    authDomain: 'no-excuses-f5c0f.firebaseapp.com',
    storageBucket: 'no-excuses-f5c0f.appspot.com',
    measurementId: 'G-EM4NHF0PP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLr0_XmpB_uB7Y9OpI5nHTytCmJ3jyygg',
    appId: '1:121552352022:android:3e5b9665ae5b0681a89637',
    messagingSenderId: '121552352022',
    projectId: 'no-excuses-f5c0f',
    storageBucket: 'no-excuses-f5c0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmI5z2svve3T9aq16nAa3CSxzzkInLRaI',
    appId: '1:121552352022:ios:532280abe5c05318a89637',
    messagingSenderId: '121552352022',
    projectId: 'no-excuses-f5c0f',
    storageBucket: 'no-excuses-f5c0f.appspot.com',
    iosClientId: '121552352022-fvaqbrgr541s3um1amlgvmrdl3o05r90.apps.googleusercontent.com',
    iosBundleId: 'com.example.noExcuses',
  );
}
